.\" (c) 2000-2001 Andreas Krennmair
.TH snake 1 "15 Feb 2000"
.SH NAME
snake \- catch as many stars as possible with your snake.
.SH SYNOPSIS
.B snake
.SH DESCRIPTION
.B snake
is a little game where you have to catch as many stars as possible with
your snake. This game is well-known on the nokia mobile phones, but I
wrote my own version for the Linux-console. It is based on the two games
"Pizza worm" and "Beer worm" that are actually better than mine (cool
graphics and stuff), but they are written for the wrong operating system (DOS).

.SH OPTIONS
none

.SH NOTES
Control the snake by using the keys i, j, k and l (guess what each of
them does :). You can customize these keys by editing the .snake file
in your home directory.

.SH BUGS
.TP
Known bugs and limitations:
.br
The "What's your name?" doesn't always work correctly.

.SH AUTHOR
Andreas Krennmair <a.krennmair@aon.at>
